version: "3.9"
services: 
    node:
        build: .
        # command: npm install tracer
        command: npm start
        volumes: 
            - .:/usr/src/app
        ports: 
            - 80:3000
            - 9229:9229
